# Generated by Django 3.1.2 on 2021-07-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0129_add_product_types_and_attributes_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mpn',
            field=models.CharField(default='AAA', max_length=50),
            preserve_default=False,
        ),
    ]
