# Generated by Django 3.1.2 on 2021-07-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0130_product_mpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mpn',
            field=models.CharField(default='BBB', max_length=50),
        ),
    ]
