# Generated by Django 3.1.2 on 2021-07-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.SmallIntegerField()),
                ('company', models.CharField(max_length=50)),
                ('item_num_id', models.IntegerField()),
                ('mpn', models.CharField(max_length=50)),
                ('qty', models.PositiveIntegerField()),
                ('offer_price', models.CharField(max_length=20)),
                ('lead_time_days', models.IntegerField()),
            ],
        ),
    ]
