import { Product } from '../generated/graphql';
export const productDataSample: Product = {
  id: "UHJvZHVjdDo3",
  name: "Intel® Celeron® Processor N3010",
  description: "test",
  descriptionJson: "test",
  productType: {
    id: "UHJvZHVjdFR5cGU6NA==",
    name: "Intel® Celeron® Processor N Series",
    hasVariants: false,
    slug: 'intel',
    isShippingRequired: true,
    isDigital: false,
    privateMetadata: [],
    metadata:[],
    privateMeta: [],
    meta: []
  },
  slug: 'test',
  chargeTaxes: false,
  visibleInListings: true,
  privateMetadata: [],
  metadata:[],
  privateMeta: [],
  meta: [],
  url: 'string',
  attributes: [
    {attribute: {
      id: "QXR0cmlidXRlOjQ=",
      slug: "manufacturer",
      privateMetadata: [],
      metadata:[],
      privateMeta: [],
      meta: [],
      __typename: "Attribute",
      productTypes: { pageInfo: { hasNextPage: false, hasPreviousPage: false}, edges: []},
      productVariantTypes: { pageInfo: { hasNextPage: false, hasPreviousPage: false}, edges: []},
      valueRequired: true,
      visibleInStorefront: true,
      filterableInStorefront: true,
      filterableInDashboard: true,
      availableInGrid: true,
      storefrontSearchPosition: 0
    }, values: [{
      id: "QXR0cmlidXRlVmFsdWU6Mw==",
      name: "Intel"
    }]},
    {attribute: {
      id: "QXR0cmlidXRlOjg=",
      slug: "ordering-code",
      privateMetadata: [],
      metadata:[],
      privateMeta: [],
      meta: [],
      __typename: "Attribute",
      productTypes: { pageInfo: { hasNextPage: false, hasPreviousPage: false}, edges: []},
      productVariantTypes: { pageInfo: { hasNextPage: false, hasPreviousPage: false}, edges: []},
      valueRequired: true,
      visibleInStorefront: true,
      filterableInStorefront: true,
      filterableInDashboard: true,
      availableInGrid: true,
      storefrontSearchPosition: 0
    }, values: [{
      id: "QXR0cmlidXRlVmFsdWU6MjQ=",
      name: "FH8066501715938"
    }]},
    {attribute: {
      id: "QXR0cmlidXRlOjc=",
      slug: "spec-code",
      privateMetadata: [],
      metadata:[],
      privateMeta: [],
      meta: [],
      __typename: "Attribute",
      productTypes: { pageInfo: { hasNextPage: false, hasPreviousPage: false}, edges: []},
      productVariantTypes: { pageInfo: { hasNextPage: false, hasPreviousPage: false}, edges: []},
      valueRequired: true,
      visibleInStorefront: true,
      filterableInStorefront: true,
      filterableInDashboard: true,
      availableInGrid: true,
      storefrontSearchPosition: 0
    }, values: [{
      id: "QXR0cmlidXRlVmFsdWU6MjA=",
      name: "SR2KM"
    }]}
  ],
  variants: [{
    id: "1",
    name: "test",
    sku: "12345",
    quantityAvailable: 50,
    privateMetadata: [],
    metadata:[],
    privateMeta: [],
    meta: [],
    trackInventory: false,
    quantity: 2,
    stockQuantity: 10,
    attributes: [],
    __typename: "ProductVariant",
    product: {
      isPublished: true,
      id: "UHJvZHVjdDo3",
      name: "Intel® Celeron® Processor N3010",
      description: "test",
      descriptionJson: "test",
      productType: {
        id: "UHJvZHVjdFR5cGU6NA==",
        name: "Intel® Celeron® Processor N Series",
        hasVariants: false,
        slug: 'intel',
        isShippingRequired: true,
        isDigital: false,
        privateMetadata: [],
        metadata:[],
        privateMeta: [],
        meta: []
      },
      slug: 'test',
      chargeTaxes: false,
      visibleInListings: true,
      privateMetadata: [],
      metadata:[],
      privateMeta: [],
      meta: [],
      url: 'string',
      attributes: [],
    },
  }],
  isPublished: true
}